# SPDX-License-Identifier: MIT-0
---
# defaults file for creating-users-and-groups

user_groups:
  - devteam
  - qateam
  - ops

password_policy:
  max_days: 90
  min_days: 1
  warn_days: 7
  inactive_days: 30

temp_password: 'Temp123'
