# SPDX-License-Identifier: MIT-0
---
# defaults file for creating-users-and-groups

user_groups:
  - devteam
  - qateam
  - ops

password_policy:
  max_days: 90
  min_days: 1
  warn_days: 7
  inactive_days: 30

# users:
#   - username: alice
#     group: devteam
#     shell: /bin/bash
#     create_home: true
#     first_login_change: true
#   - username: bob
#     group: qateam
#     shell: /bin/bash
#     create_home: true
#     first_login_change: true
#   - username: alex
#     group: devteam
#     shell: /bin/bash
#     create_home: true
#     first_login_change: true
#   - username: charlie
#     group: ops
#     shell: /bin/bash
#     create_home: true
#     first_login_change: true
