# SPDX-License-Identifier: MIT-0
---
# defaults file for prepare-server

base_packages:
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - chrony
  - tzdata
  - needrestart
  - acl
