# SPDX-License-Identifier: MIT-0
---
# defaults file for prepare-server

base_packages:
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - chrony
  - tzdata
  - needrestart
  - bat
  - acl
  - auditd
  - audispd-plugins

apt_upgrade: full
apt_cache_valid_time: 3600
apt_autoremove: true
apt_autoclean: true

name_timezone: Europe/Moscow
