# SPDX-License-Identifier: MIT-0
---
# defaults file for umask

umask_path_profiled: /etc/profile.d

umask_file_permissions:
  root: root
  vagrant: vagrant
  mode: '0644'

umask_file:
  name: 10-umask-profile.sh
  content: |
    umask 027

umask_path_test: /umask-test
umask_test_file:
  name: umask-test
  mode: '0775'
